### PR TITLE
Fixed broken link to module Locale::XGettext.

### PR DESCRIPTION
**Pull request by manwar**
Hi @gflohr 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by gflohr** [comment]
Thanks!

**Comment by gflohr** [comment]
@manwar: Do you need a new CPAN release for that?

**Comment by manwar** [comment]
Not really :-)

**Comment by gflohr** [comment]
Okay. Then thanks again and cu in Glasgow! :)

**Pull request merged**
